# Generated by Django 6.0.3 on 2026-03-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoriaxd',
        ),
    ]
