# Generated by Django 6.0.3 on 2026-03-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_categoria_producto_categoriaxd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoria1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaxd',
            new_name='categoria',
        ),
    ]
