# Generated by Django 6.0.3 on 2026-03-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_categoria_categoria1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria1',
            new_name='Categoria',
        ),
    ]
